spring:
  datasource:
    url: jdbc:mysql://localhost:3306/slowme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: slowme_admin
    password: Pa$$Word!2#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET time_zone = '+09:00'
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  config: classpath:config/log/log4j2-local.xml

slowme:
  realtime:
    enabled: true
    ws-endpoint: /ws
    redis-channel: slowme:room-events

